feat: add details to file structures to show test assets and types
strimzi/strimzi-ui pull request #104
Opened 2020-11-12 16:23 UTC by JQrdan

Closes: #100

Signed-off-by: Jordan <jordan.tucker1@ibm.com>

2020-11-13 08:42 UTC, matthew-chirgwin approved these changes

2020-11-13 08:43 UTC, scholzj approved these changes

2020-11-13 10:11 UTC, nictownsend requested changes
Minor changes

2020-11-13 10:11 UTC, nictownsend commented on client/Hooks/README.md
>      Hook.ts
UseFoo.*

2020-11-13 10:11 UTC, nictownsend commented on client/Contexts/README.md
> +    Context.assets.ts
FeatureFlagContext

2020-11-13 10:19 UTC, nictownsend commented on client/Hooks/README.md
>      Hook.ts
Actually, we should name the hook `Foo`, and then it's called `useFoo` when exported?

2020-11-16 09:46 UTC, matthew-chirgwin requested changes
https://github.com/strimzi/strimzi-ui/blob/master/docs/Architecture.md#file-name-conventions also needs an update to reference the `types.ts` file

2020-11-16 12:00 UTC, nictownsend approved these changes

2020-11-16 12:00 UTC, nictownsend commented
Approved - but https://github.com/strimzi/strimzi-ui/pull/104#discussion_r522856913 would be nice if you agree

2020-11-16 13:01 UTC, JQrdan commented
> Approved - but [#104 (comment)](https://github.com/strimzi/strimzi-ui/pull/104#discussion_r522856913) would be nice if you agree

I've got mixed feelings about this, I'd rather keep the file name as `useFoo` but am open to changing it if others think it should change

2020-11-16 16:03 UTC, pmuir commented on client/Elements/README.md
> +- HEading.assets.ts are the test assets for this component
type on last line I think

2020-11-16 16:03 UTC, pmuir approved these changes

2020-11-17 08:51 UTC, matthew-chirgwin commented
> > Approved - but [#104 (comment)](https://github.com/strimzi/strimzi-ui/pull/104#discussion_r522856913) would be nice if you agree
> 
> I've got mixed feelings about this, I'd rather keep the file name as `useFoo` but am open to changing it if others think it should change

I would vote to keep it as is. Just imagining the case of someone using the `useFoo` hook and wanting to find it in the codebase. You would hope they would realise `useFoo` lives in the `Foo` directory, but `useFoo` is explicit

2020-11-17 13:25 UTC, dlabaj approved these changes

2020-11-17 14:09 UTC, matthew-chirgwin approved these changes

2020-11-17 14:09 UTC, merged