feat: add dependency approach doc
strimzi/strimzi-ui pull request #32
Opened 2020-10-02 10:44 UTC by matthew-chirgwin

- adds section to cover dependency approach

Closes: #31

Signed-off-by: Matthew Chirgwin <chirmatt@uk.ibm.com>

2020-10-02 10:52 UTC, JQrdan requested changes
Sounds good to me, just some minor changes needed

2020-10-02 10:52 UTC, JQrdan commented on docs/Architecture.md
> +This UI will make use of a number of third party dependencies to operate at develop, test, and runtime. The will range from helper tools such as Webpack, to frameworks, such as React. The `package.js
The second sentence reads weird to me

2020-10-02 10:52 UTC, JQrdan commented on docs/Architecture.md
> +
E.g. and I.e. instead of eg and ie

2020-10-05 08:30 UTC, JQrdan approved these changes
LGTM

2020-10-05 08:36 UTC, scholzj approved these changes

2020-10-06 17:26 UTC, dlabaj reviewed
Thanks for submitting this.  A few comments / questions.

2020-10-06 17:26 UTC, dlabaj commented on docs/Architecture.md
> +A UI typically allows a user to interact with resources. These resources are types of known entity (E.g. a Topic), which typically can be created, read, updated or deleted. Similarly, entities are of
I think we can get rid of the word Similarly and just use "Entities are often..."

2020-10-06 17:26 UTC, dlabaj commented on docs/Architecture.md
> +A UI typically allows a user to interact with resources. These resources are types of known entity (E.g. a Topic), which typically can be created, read, updated or deleted. Similarly, entities are of
Same with Equally... could just say "The ability..."

2020-10-06 17:26 UTC, dlabaj commented on docs/Architecture.md
> +This UI will make use of a number of third party dependencies to operate at develop, test, and runtime. This will range from helper tools such as Webpack, to frameworks, like React. The `package.json
We could get rid of the `npm publish` part since we are not publishing this package, and change it to `npm build` everywhere instead.

2020-10-06 17:26 UTC, dlabaj commented on docs/Architecture.md
> +The Strimzi-ui will not be published. Instead, it will consume a number of packages, and be built to provide a UI. Some of these packages will be used and shipped directly, but some will also generat
Can we consolidate this section with the one above, so we only have 3 bullets instead of 5 bullets (dependencies, devDependencies, and peerDependencies)?

2020-10-06 17:26 UTC, dlabaj commented on docs/Architecture.md
> +- `dependencies` are any dependency which are either shipped bundled in the built output via direct usage (E.g. React), included in the dockerfile which will run the UI (E.g. Express) or generate out
I noticed `npm audit` does audit devDependencies as well.  Wondering if we can get rid of the generate output part of this.  I believe having them in devDependencies will work correctly for us.

2020-10-07 14:19 UTC, matthew-chirgwin commented on docs/Architecture.md
> +A UI typically allows a user to interact with resources. These resources are types of known entity (E.g. a Topic), which typically can be created, read, updated or deleted. Similarly, entities are of
Both updated - good suggestions :)

2020-10-07 14:22 UTC, matthew-chirgwin commented on docs/Architecture.md
> +This UI will make use of a number of third party dependencies to operate at develop, test, and runtime. This will range from helper tools such as Webpack, to frameworks, like React. The `package.json
This was intended to be a quick summary of the normal npm approach to dependencies, with the following sentences/paragraphs explaining the difference in approach we take. I will update the wording to be more clear here.

2020-10-07 14:29 UTC, matthew-chirgwin commented on docs/Architecture.md
> +- `dependencies` are any dependency which are either shipped bundled in the built output via direct usage (E.g. React), included in the dockerfile which will run the UI (E.g. Express) or generate out
`npm audit` is one tool which can list both normal and dev dependencies. There are others which cannot/do not however (just reading the dependencies section). Plus, some generated code is included in/amongst the code we write in the built package, as if we imported it.

2020-10-07 14:31 UTC, matthew-chirgwin commented
Thank you for the comments @dlabaj / @JQrdan - I have rebased and updated the PR given these. If there are no more comments I will look to merge this tomorrow

2020-10-07 15:53 UTC, dlabaj commented on docs/Architecture.md
> +- `dependencies` are any dependency which are either shipped bundled in the built output via direct usage (E.g. React), included in the dockerfile which will run the UI (E.g. Express) or generate out
okay then this is fine.  Thanks for the clarification.

2020-10-07 15:54 UTC, dlabaj commented on docs/Architecture.md
> +This UI will make use of a number of third party dependencies to operate at develop, test, and runtime. This will range from helper tools such as Webpack, to frameworks, like React. The `package.json
No worries.  I just didn't want someone to get confused reading this.  Thanks again.

2020-10-08 07:58 UTC, merged