chore: ignore .idea folder for lint (#63)
strimzi/strimzi-ui pull request #66
Opened 2020-10-30 11:44 UTC by pmuir

Signed-off-by: Pete Muir <pmuir@bleepbleep.org.uk>

2020-10-30 11:49 UTC, matthew-chirgwin requested changes

2020-10-30 11:49 UTC, matthew-chirgwin commented on docs/Build.md
> +| `/(\.ts                     | tsx)\$/`                                                                                                |
I saw the same in #65 , but this breaks the table formatting - I take it the linter did this?

2020-10-30 12:07 UTC, scholzj approved these changes

2020-10-30 12:17 UTC, matthew-chirgwin commented on docs/Build.md
> +| `/(\.ts                     | tsx)\$/`                                                                                                |
Also @pmuir - PR #65 will resolve both changes made in this PR. That being the case, is this PR needed?

2020-11-02 15:08 UTC, pmuir commented
Yes, the linter did it, so I guess we need to not lint the file

2020-11-02 15:08 UTC, closed without merging