Upgrade to webpack 5
strimzi/strimzi-ui pull request #79
Opened 2020-11-03 18:45 UTC by pmuir

* move all webpack dependencies and babel to devDependencies
* upgrade all webpack dependencies to latest version
* switch to webpack serve
* switch to css-mimimizer-webpack-plugin from optimize-css-assets-webpack-plugin as suggested by optimize-css-assets-webpack-plugin maintainers

Signed-off-by: Pete Muir <pmuir@bleepbleep.org.uk>

2020-11-03 18:46 UTC, pmuir commented
This is the big changes required for webpack 5 & module federation. I'll add the federation plugin in a subsequent PR.

2020-11-04 09:55 UTC, nictownsend commented
@pmuir - what are your thoughts over `deps` vs `devDeps` - @matthew-chirgwin and I have previously pivoted from `deps` meaning "only things you need to run the project after building", to also include "anything that creates build output".

Argument being - automated scans that check for vulnerable libraries need to flag things that could be injecting code into the build (webpack for e.g) - but they don't need to run against things like jest or helper modules for testing.

2020-11-04 18:00 UTC, nictownsend requested changes
Overall LGTM - but looks like webpack is not happy with storybook, and would be good to get thoughts on my comment above too, thanks!

2020-11-09 09:40 UTC, pmuir commented
AIUI `deps` is only for production dependencies - see https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file. With things like this I would tend to follow the official advice.

I think that if the tool isn't scanning your development time dependencies and you want it to, you probably want to configure the tool, not deviate from standard packaging.

2020-11-09 09:40 UTC, pmuir commented
And yes, storybook build is broken - see issue.

2020-11-25 18:09 UTC, pmuir commented
@b1zzu managed to find an upgraded html-webpack-plugin that will make this work.

2020-11-30 09:42 UTC, nictownsend commented
> AIUI `deps` is only for production dependencies - see https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file. With things like this I would tend to follow the official advice.
> 
> I think that if the tool isn't scanning your development time dependencies and you want it to, you probably want to configure the tool, not deviate from standard packaging.

@matthew-chirgwin I'm inclined to agree (with assumption that whatever tooling is picked can be flagged to add certain dev tooling to an allow list)

2020-12-01 18:42 UTC, pmuir commented
@matthew-chirgwin can we get this merged?

2020-12-02 11:22 UTC, matthew-chirgwin commented
> > AIUI `deps` is only for production dependencies - see https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file. With things like this I would tend to follow the official advice.
> > I think that if the tool isn't scanning your development time dependencies and you want it to, you probably want to configure the tool, not deviate from standard packaging.
> 
> @matthew-chirgwin I'm inclined to agree (with assumption that whatever tooling is picked can be flagged to add certain dev tooling to an allow list)

@pmuir / @nictownsend - re dependencies, the issue for me is what we are producing is not an npm package we will upload to npm, and moreover, the definition of production and development dependancies do not fit what we are producing either. Hence the initial write up here: https://github.com/strimzi/strimzi-ui/blob/master/docs/Architecture.md#dependency-management

If we were producing a package which would be published to NPM, we would and should follow the convention - it would be mad not to, as that is what consumers will expect. However, we are not producing an NPM package in this repo. Rather, we are building a UI for Strimzi, which will be distributed via Dockerfile so it can be deployed by the Strimzi operator. Thus, really we are a consumer of the NPM registry, and thus, all we would look to do is pull dependencies we need to make the UI. For me, there then is a question: how should we classify those dependencies?

In my opinion, the npm dependency vs dev dependency definition (originally intended for node modules/packages) does not work/has not aged well for more modern web UIs. `Packages required by your application in production.` - when is `production` for a built UI? A good number of our 3rd party dependancies effect/are used in the ‘built’ code - ie they either take what we write and either compile, transform, or add their own inserts to in addition/based on what we write. 

Hypothetically, if we use a webpack plugin (for example) as a dev dependency (the traditional location for npm published packages), and it inserts a polyfill to our built bundle, we would ship it as a part of our built UI output. If that polyfill is somehow compromised, and malicious code inserted, that malicious code is then shipped as well. This would mean the malicious code could then effect consumers/users (either as consumers of an NPM package, or in our case, with malicious code running in the user’s browser or on the UI server).

npm’s own definition of a dependency is `Packages required by your application in production.`. If it is built, or results in built output, for me this makes it `required` in production. Hence the guidance in the link above.

These transpiling/compiling/polyfilling type libraries are in an interesting grey area - one for which the normal dependency vs dev dependency classification doesn’t really fit. Peer is not right either - as a consumer may not need to use the same build stack as us. It also doesn’t help either differentiating these libraries and what they do is non trivial (ie webpack is the runtime, and doesn’t modify code, but webpack includes plugins which we use/does). The general answer I have seen elsewhere in these cases is list everything as a dependency - as you need them all to develop the codebase in question. I err on that, as there is still a useful differentiation to make between what we ship, and what we use to develop.

With sensible differentiation of dependencies, we can still get value from production and development classified packages. For one, at build time, we can install and include just the dependencies we need [in the dockerfile at runtime.](https://github.com/strimzi/strimzi-ui/blob/26898902e404b4a4736f2fae3b106a63218bf5bc/build/dockerfile#L18) _Note: this will include build dependancies as well, but as per the above without another classification, this is a scenario I think is preferable to ship a few extra things which are never refernced in the dockerfile vs the whole set of dependencies._ In addition, by clarifying dependencies sensibly, we get value from tools like `npm audit`, which will flag issues with the packages we use directly or indirectly, and in our case, where these issues would manifest - ie dev only, production only, both etc.

In short, without further discussion/agreement  to change strategy, I would reject this PR on the grounds a few dependencies are not in the right section as is today, with the reasons for those classifications as is hopefully described here. Really this is a wider issue, one that npm should guide on. I suspect for legacy reasons however, things would not change. Otherwise @pmuir I have no objection/issue with the change.

2020-12-02 11:52 UTC, pmuir commented
I can change them back to what they were before - it's an weird layout but whatever, it doesn't really matter.

2020-12-07 20:01 UTC, pmuir commented
@matthew-chirgwin ok - dependencies are now just upgraded.

2020-12-09 09:19 UTC, matthew-chirgwin approved these changes

2020-12-09 09:19 UTC, matthew-chirgwin commented on package.json
>      "webpack-dev-server": "^3.11.0",
Wont block the PR on it, but as `webpack serve` is being used, is dev server still needed? Perhaps worth removing in the next PR if so?

2020-12-09 09:25 UTC, pmuir commented
Yes, it's still needed. They only changed the command, not the dependencies.

On Wed, 9 Dec 2020 at 09:20, Matthew Chirgwin <notifications@github.com>
wrote:

> *@matthew-chirgwin* approved this pull request.
> ------------------------------
>
> In package.json
> <https://github.com/strimzi/strimzi-ui/pull/79#discussion_r539138314>:
>
> > @@ -146,8 +147,8 @@
>      "ts-node": "^9.0.0",
>      "tsconfig-paths": "^3.9.0",
>      "tsconfig-paths-webpack-plugin": "^3.3.0",
> -    "webpack-bundle-analyzer": "^3.8.0",
> -    "webpack-cli": "^3.3.12",
> +    "webpack-bundle-analyzer": "^3.9.0",
> +    "webpack-cli": "^4.1.0",
>      "webpack-dev-server": "^3.11.0",
>
> Wont block the PR on it, but as webpack serve is being used, is dev
> server still needed? Perhaps worth removing in the next PR if so?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/strimzi/strimzi-ui/pull/79#pullrequestreview-547982057>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABGQQPVVUB3HASMIO2XBNLST46MTANCNFSM4TJDQYUQ>
> .
>

2020-12-09 09:36 UTC, scholzj approved these changes

2020-12-09 09:44 UTC, merged